kind: pipeline
name: default
type: docker

steps:
  - name: test script
    image: curlimages/curl
    commands: 
    - export PLUGIN_CITY=BFS
    - sh script.sh
    
  - name: git-leak
    image: plugins/gitleaks

  - name: snyk image scan
    image: plugins/drone-snyk
    privileged: true
    settings:
      image: mcr.microsoft.com/dotnet/sdk:5.0
      debug: true
      username:
        from_secret: username
      password:
        from_secret: password
      snyk:
        from_secret: snyk
      fail_on_issues: false

  - name: publish image to dockerhub
    image: plugins/docker
    settings:
      repo: plugins/drone_playground
      auto_tag: true
      username:
        from_secret: username
      password:
        from_secret: password
    when:
    status:
    - success
    - failure
